// ==UserScript==
// @name         HKs Merc-C-Que Launcher Drag Guard
// @namespace    hks-merc-c-que-launcher-drag-guard
// @version      1.0.0
// @description  Temporary diagnostic fix: prevents a launcher drag from being treated as a restore click.
// @author       HairyKary
// @match        https://www.torn.com/*
// @match        https://torn.com/*
// @run-at       document-start
// @noframes
// ==/UserScript==

(() => {
  'use strict';

  const LAUNCHER_ID = 'hkmcq-launcher';
  const DRAG_THRESHOLD = 4;
  const SUPPRESS_MS = 1500;

  let drag = null;
  let suppressUntil = 0;

  function isLauncherTarget(target) {
    return target instanceof Element && !!target.closest(`#${LAUNCHER_ID}`);
  }

  document.addEventListener('pointerdown', event => {
    if (!isLauncherTarget(event.target)) return;
    drag = {
      pointerId: event.pointerId,
      startX: event.clientX,
      startY: event.clientY,
      moved: false
    };
  }, true);

  document.addEventListener('pointermove', event => {
    if (!drag || event.pointerId !== drag.pointerId) return;
    if (
      Math.abs(event.clientX - drag.startX) >= DRAG_THRESHOLD ||
      Math.abs(event.clientY - drag.startY) >= DRAG_THRESHOLD
    ) {
      drag.moved = true;
    }
  }, true);

  document.addEventListener('pointerup', event => {
    if (!drag || event.pointerId !== drag.pointerId) return;
    if (drag.moved) suppressUntil = Date.now() + SUPPRESS_MS;
    drag = null;
  }, true);

  document.addEventListener('pointercancel', event => {
    if (drag && event.pointerId === drag.pointerId) drag = null;
  }, true);

  document.addEventListener('click', event => {
    if (!isLauncherTarget(event.target)) return;
    if (Date.now() >= suppressUntil) return;

    suppressUntil = 0;
    event.preventDefault();
    event.stopImmediatePropagation();
    console.info('[Merc-C-Que] Suppressed launcher click generated by drag.');
  }, true);
})();
